# The Site Configuration
theme: jekyll-theme-chirpy
lang: en
timezone: Africa/Cairo # التوقيت الخاص بمصر

# jekyll-seo-tag settings
# ↓ --------------------------

title: MObinXIV # اسمك البرمجي اللي هيظهر فوق
tagline: Software Engineer | Java & Spring Boot Enthusiast # الوصف المختصر تحت الاسم
description: >-
  A blog dedicated to Software Engineering, Java development,
  and the intersection of technology and psychology.

# الرابط الأساسي لموقعك (بدون / في الآخر)
url: "https://MObinXIV.github.io"

github:
  username: MObinXIV

social:
  name: Mohamed Jamal # اسمك الكامل اللي هيظهر في حقوق النشر
  email: example@domain.com # غيره لإيميلك الحقيقي لو حابب
  links:
    - https://github.com/MObinXIV
    - https://www.linkedin.com/in/mobinxiv # تأكد من صحة رابط لينكد إن الخاص بك

# ↑ --------------------------

# الإعدادات المفضلة للألوان (سيبها فاضية عشان يظهر زرار التبديل بين الـ Dark/Light)
theme_mode:

# صورة الـ Avatar (الصورة الشخصية في القائمة الجانبية)
# يمكنك وضع رابط صورتك هنا لاحقاً
avatar: 'https://github.com/MObinXIV.png' # دي هتسحب صورتك من جيت هاب تلقائياً

# boolean type, the global switch for TOC in posts.
toc: true

# PWA feature (الموقع يكون قابل للتثبيت كأبلكيشن)
pwa:
  enabled: true

paginate: 10
baseurl: "" # سيبها فاضية طالما الموقع هو الـ Primary

# ------------ باقي الإعدادات الافتراضية (لا تغيرها إلا للضرورة) ------------------

kramdown:
  footnote_backlink: "&#8617;&#xfe0e;"
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: /:title/

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"
